language: python

dist: xenial

python:
  - '3.7'

env: TRAVIS=true

install:
  - pip install --upgrade setuptools pip
  - pip install cython
  - pip install -r requirements.txt
  - pip install qgrid
  - pip install nbval
  - pip install vtk
  - pip install pyevtk
  - pip install dataclasses emg3d pyvista panel discretize
# - pip install --user travis-sphinx
  - export PATH="./bin:$PATH"
script:

#  - pytest -v notebooks/integrations/ --nbval-lax --ignore-glob='*discret*'
#  - pytest -v notebooks/examples/ --nbval-lax --current-env --ignore-glob='*pography*' --ignore-glob='*lesmodel*' --ignore-glob='*Course*'
#  - pytest -v notebooks/tutorials/ --nbval-lax --current-env --ignore-glob='*ch1-6*' --ignore-glob='ch1-7*' --ignore-glob='*ch1-10*' --ignore-glob='*MaskedMarchinCube_Onlap_relations*'
#  - pytest


stages:
  - build and test
  - deploy
#after_success:
#   - travis-sphinx deploy

jobs:
include:
    - stage: build and test # This stage builds and lints in parallel
      name: Build
      script: pipenv run make html # build the docs
    - stage: deploy
      name: Deploy to GitHub Pages
      if: (NOT type IN (pull_request)) AND (branch = sphinx-gallery) # only deploy if merging on master
      script: pipenv run make html
      deploy:
        provider: pages # deploy on github pages
        skip_cleanup: true
        github_token: "$token" # defined via the Travis interface
        local_dir: build/html
cache: pip

